/*
 * Zmanim Java API
 * Copyright (C) 2004-2026 Eliyahu Hershfeld
 *
 * This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General
 * Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful,but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 * details.
 * You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA,
 * or connect to: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
 */
package com.kosherjava.zmanim.util;

import java.lang.reflect.Method;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import com.kosherjava.zmanim.AstronomicalCalendar;

/**
 * A class used to format both  {@link java.time.Instant} times generated by the Zmanim package as well as {@link
 * java.time.Duration}} used for temporal hours / sha'os zmaniyos. For example the {@link
 * com.kosherjava.zmanim.AstronomicalCalendar#getTemporalHour()} returns the length of the hour as a <code>Duration</code>.
 * 
 * @author &copy; Eliyahu Hershfeld 2004 - 2026
 */
public class ZmanimFormatter {
	/**
	 * Setting to prepend a zero to single digit hours.
	 * @see #setSettings(boolean, boolean, boolean)
	 */
	private boolean prependZeroHours = false;

	/**
	 * Should seconds be used in formatting time.
	 * @see #setSettings(boolean, boolean, boolean)
	 */
	private boolean useSeconds = false;

	/**
	 * Should milliseconds be used in formatting time.
	 * @see #setSettings(boolean, boolean, boolean)
	 */
	private boolean useMillis = false;

	/**
	 * the formatter for minutes as seconds.
	 */
	private final static DecimalFormat minuteSecondNF = new DecimalFormat("00");

	/**
	 * the formatter for hours.
	 */
	private final DecimalFormat hourNF;

	/**
	 * the formatter for minutes as milliseconds.
	 */
	private final static DecimalFormat milliNF = new DecimalFormat("000");

	/**
	 * The SimpleDateFormat class.
	 * @see #setDateTimeFormatter(DateTimeFormatter)
	 */
	private DateTimeFormatter dateTimeFormatter;
	
	/**
	 * The TimeZone class.
	 * @see #setZoneId(ZoneId)
	 */
	private ZoneId zoneId = null;


	/**
	 * Method to return the <code>ZoneId</code>.
	 * @return the ZoneId
	 */
	public ZoneId getZoneId() {
		return zoneId;
	}

	/**
	 * Method to set the TimeZone.
	 * @param zoneId the ZoneId to set
	 */
	public void setZoneId(ZoneId zoneId) {
		this.zoneId = zoneId;
	}

	/**
	 * Format using hours, minutes, seconds and milliseconds using the xsd:time format. This format will return
	 * 00.00.00.0 when formatting 0.
	 */
	public static final int SEXAGESIMAL_XSD_FORMAT = 0;

	/**
	 * Defaults to {@link #SEXAGESIMAL_XSD_FORMAT}.
	 * @see #setTimeFormat(int)
	 */
	private int timeFormat = SEXAGESIMAL_XSD_FORMAT;

	/**
	 * Format using standard decimal format with 5 positions after the decimal.
	 */
	public static final int DECIMAL_FORMAT = 1;

	/** Format using hours and minutes. */
	public static final int SEXAGESIMAL_FORMAT = 2;

	/** Format using hours, minutes and seconds. */
	public static final int SEXAGESIMAL_SECONDS_FORMAT = 3;

	/** Format using hours, minutes, seconds and milliseconds. */
	public static final int SEXAGESIMAL_MILLIS_FORMAT = 4;
	
	/**
	 * Format using the XSD Duration format. This is in the format of PT1H6M7.869S (P for period (duration), T for time,
	 * H, M and S indicate hours, minutes and seconds.
	 */
	public static final int XSD_DURATION_FORMAT = 5;

	/**
	 * Constructor that defaults to this will use the format "h:mm:ss" for dates and 00.00.00.0 for {@link java.time.Duration}.
	 * @param zoneId the <code>ZoneId</code> Object
	 */
	public ZmanimFormatter(ZoneId zoneId) {
		this(0, DateTimeFormatter.ofPattern("h:mm:ss"), zoneId);
	}

	/**
	 * ZmanimFormatter constructor using a formatter
	 * 
	 * @param format The formatting style to use. For the time of an hour and a half, Using
	 *     {@link #SEXAGESIMAL_XSD_FORMAT} (the default) will format the time as "01:30:00.000", and half an hour as "00:30:00.000".
	 *     {@link #SEXAGESIMAL_MILLIS_FORMAT} will format the time as "1:30:00.000", and half an hour as "0:30:00.000".
	 *     {@link #SEXAGESIMAL_SECONDS_FORMAT} will format the an hour and a half as "1:30:00", and half an hour as "0:30:00".
	 *     {@link #SEXAGESIMAL_FORMAT} will format the time as "1:30", and half an hour as "0:30".
	 *     {@link #XSD_DURATION_FORMAT} will format the time as : "PT1H30M", and half an hour as "PT30M".
	 * @param dateTimeFormatter the <code>DateTimeFormatter</code> Object
	 * @param zoneId the <code>ZoneId</code> Object
	 */
	public ZmanimFormatter(int format, DateTimeFormatter dateTimeFormatter, ZoneId zoneId) {
		setZoneId(zoneId);
		setTimeFormat(format);
		String hourFormat = "0";
		if (prependZeroHours) {
			hourFormat = "00";
		}
		this.hourNF = new DecimalFormat(hourFormat);
		setDateTimeFormatter(dateTimeFormatter.withZone(zoneId));
	}

	/**
	 * Sets the format to use for formatting.
	 * 
	 * @param format the format constant to use. See {@link #ZmanimFormatter(int, DateTimeFormatter, ZoneId)} for documentation on
	 *         the formats.
	 */
	public void setTimeFormat(int format) {
		this.timeFormat = format;
		switch (format) {
		case SEXAGESIMAL_XSD_FORMAT:
			setSettings(true, true, true);
			break;
		case SEXAGESIMAL_FORMAT:
			setSettings(false, false, false);
			break;
		case SEXAGESIMAL_SECONDS_FORMAT:
			setSettings(false, true, false);
			break;
		case SEXAGESIMAL_MILLIS_FORMAT:
			setSettings(false, true, true);
			break;
		case XSD_DURATION_FORMAT:
			break; // the settings are N/A for this 
		default: throw new IllegalArgumentException("An invalid time format of " + format +
				" was set. Please see the documentation for the list of valid formats.");
		}
	}

	/**
	 * Sets the SimpleDateFormat Object
	 * @param dateTimeFormatter the <code>DateTimeFormatter</code> Object to set
	 */
	public void setDateTimeFormatter(DateTimeFormatter dateTimeFormatter) {
		this.dateTimeFormatter = dateTimeFormatter;
	}

	/**
	 * returns the <code>DateTimeFormatter</code> Object.
	 * @return the <code>DateTimeFormatter</code> Object.
	 */
	public DateTimeFormatter getDateTimeFormatter() {
		return this.dateTimeFormatter;
	}

	/**
	 * Sets various format settings.
	 * @param prependZeroHours if to prepend a zero for single digit hours (so that 1 o'clock is displayed as 01)
	 * @param useSeconds should seconds be used in the time format
	 * @param useMillis should milliseconds be used in formatting time.
	 */
	private void setSettings(boolean prependZeroHours, boolean useSeconds, boolean useMillis) {
		this.prependZeroHours = prependZeroHours;
		this.useSeconds = useSeconds;
		this.useMillis = useMillis;
	}

	/**
	 * A method that formats milliseconds into a time format of "00:00", "00:00:00" or "00:00:00.000" depending on various settings
	 * in the formatter.
	 * 
	 * @param duration The duration to format.
	 * @return String The formatted <code>String</code>
	 */
	public String format(Duration duration) {
		if (duration == null) {
			duration = Duration.ZERO;
		}
		
		if (this.timeFormat == XSD_DURATION_FORMAT) {
			return formatXSDDurationTime(duration);
		}
		
		StringBuilder sb = new StringBuilder();
		if (duration.isNegative()) {
			sb.append("-");
		}
		
		Duration absDuration = duration.abs();
		
		long hours = absDuration.toHours();
		long minutes = absDuration.toMinutes() % 60;
		long seconds = absDuration.toSeconds() % 60;
		long milliseconds = absDuration.toMillis() % 1000;
		
		sb.append(this.hourNF.format(hours));
		sb.append(":");
		sb.append(minuteSecondNF.format(minutes));
		
		if (this.useSeconds) {
			sb.append(":");
			sb.append(minuteSecondNF.format(seconds));
		}
		if (this.useMillis) {
			sb.append(".");
			sb.append(milliNF.format(milliseconds));
		}
		
		return sb.toString();
	}

	/**
	 * Formats an <code>Instant</code> using this class's {@link #getDateTimeFormatter()}.
	 * 
	 * @param instant the <code>Instant</code> to format
	 * @param zoneId the {@link java.time.ZoneId ZoneId} used to help format based on the <code>Instant</code>'s DST and other
	 *         settings.
	 * @return the formatted String
	 * @see #formatXSDateTime(Instant)
	 */
	public String formatDateTime(Instant instant, ZoneId zoneId) {
		ZonedDateTime dateTime = instant.atZone(zoneId);
		return this.getDateTimeFormatter().format(dateTime);
	}
	
	/**
	 * Format the <code>Instant</code> using the format "yyyy-MM-dd'T'HH:mm:ssXXX".
	 * @param instant the <code>Instant</code> to format.
	 * @return the <code>Instant</code> formatted using the format "yyyy-MM-dd'T'HH:mm:ssXXX
	 */
	public String formatXSDateTime(Instant instant) {
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX").withZone(getZoneId());
		return formatter.format(instant);
	}

	/**
	 * This returns the xml representation of an xsd:duration object. This simply uses {@link Duration#toString()} that formats it
	 * in the standard XSD ISO-8601 (e.g., "PT1H30M")
	 * 
	 * @param duration the duration to format
	 * @return the xsd:duration ISO-8601 formatted String
	 */
	public String formatXSDDurationTime(Duration duration) {
		if (duration == null) {
			return "";
		}
		return duration.toString(); // Java's native toString() outputs a standard XSD ISO-8601 (e.g., "PT1H30M")
	}

	/**
	 * A method that returns an XML formatted <code>String</code> representing the serialized <code>Object</code>. The
	 * format used is:
	 * 
	 * <pre>
	 *  &lt;AstronomicalTimes date=&quot;1969-02-08&quot; type=&quot;com.kosherjava.zmanim.AstronomicalCalendar algorithm=&quot;US Naval Almanac Algorithm&quot; location=&quot;Montreal, Quebec&quot; latitude=&quot;45.497&quot; longitude=&quot;-73.63&quot; elevation=&quot;85.0&quot; timeZoneName=&quot;Eastern Standard Time&quot; timeZoneID=&quot;America/New_York&quot; timeZoneOffset=&quot;-5&quot;&gt;
	 *     &lt;SeaLevelSunset&gt;1969-02-08T17:11:26-05:00&lt;/SeaLevelSunset&gt;
	 *     &lt;TemporalHour&gt;PT50M23.259S&lt;/TemporalHour&gt;
	 *     ...
	 *   &lt;/AstronomicalTimes&gt;
	 * </pre>
	 * 
	 * If a zman does not occur, the value "N/A" will be returned.
	 * 
	 * Note that the output uses the <a href="http://www.w3.org/TR/xmlschema11-2/#dateTime">xsd:dateTime</a> format for
	 * times such as sunrise, and <a href="http://www.w3.org/TR/xmlschema11-2/#duration">xsd:duration</a> format for
	 * times that are a duration such as the length of a
	 * {@link com.kosherjava.zmanim.AstronomicalCalendar#getTemporalHour() temporal hour}. The output of this method is
	 * returned by the {@link #toString() toString}.
	 * 
	 * @param astronomicalCalendar the AstronomicalCalendar Object
	 * 
	 * @return The XML <code>String</code> formatted as described above.
	 * 
	 * @todo Add proper schema, and support for nulls. XSD duration (for solar hours), should probably return nil and not P.
	 */
	public static String toXML(AstronomicalCalendar astronomicalCalendar) {
		ZmanimFormatter formatter = new ZmanimFormatter(ZmanimFormatter.SEXAGESIMAL_XSD_FORMAT, DateTimeFormatter.ofPattern(
				"yyyy-MM-dd'T'HH:mm:ss"), astronomicalCalendar.getGeoLocation().getZoneId());
		DateTimeFormatter xsdFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX")
				.withZone(astronomicalCalendar.getGeoLocation().getZoneId());
		DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");
		df = df.withZone(astronomicalCalendar.getGeoLocation().getZoneId());

		LocalDate localDate = astronomicalCalendar.getLocalDate();
		GeoLocation geoLocation = astronomicalCalendar.getGeoLocation();
		ZonedDateTime lastMidnight = ZonedDateTime.of(astronomicalCalendar.getLocalDate(), LocalTime.MIDNIGHT, astronomicalCalendar.getGeoLocation().getZoneId());
		double offsetHours = lastMidnight.getOffset().getTotalSeconds() / 3600.0;
		String timeZoneName = lastMidnight.format(DateTimeFormatter.ofPattern("zzzz", Locale.getDefault()));

		StringBuilder sb = new StringBuilder("<");
		boolean isAstronomicalCalendar = astronomicalCalendar.getClass().getName().equals("com.kosherjava.zmanim.AstronomicalCalendar");
		boolean isComprehensiveZmanimCalendar = astronomicalCalendar.getClass().getName().equals("com.kosherjava.zmanim.ComprehensiveZmanimCalendar");
		boolean isZmanimCalendar = astronomicalCalendar.getClass().getName().equals("com.kosherjava.zmanim.ZmanimCalendar");
		if (isAstronomicalCalendar) {
			sb.append("AstronomicalTimes");
		} else if (isComprehensiveZmanimCalendar) {
			sb.append("Zmanim");
		} else if (isZmanimCalendar) {
			sb.append("BasicZmanim");
		}
		sb.append(" date=\"").append(df.format(localDate)).append("\"");
		sb.append(" type=\"").append(astronomicalCalendar.getClass().getName()).append("\"");
		sb.append(" algorithm=\"").append(astronomicalCalendar.getAstronomicalCalculator().getCalculatorName()).append("\"");
		sb.append(" location=\"").append(astronomicalCalendar.getGeoLocation().getLocationName()).append("\"");
		sb.append(" latitude=\"").append(astronomicalCalendar.getGeoLocation().getLatitude()).append("\"");
		sb.append(" longitude=\"").append(astronomicalCalendar.getGeoLocation().getLongitude()).append("\"");
		sb.append(" elevation=\"").append(astronomicalCalendar.getGeoLocation().getElevation()).append("\"");
		sb.append(" timeZoneName=\"").append(timeZoneName).append("\"");
		sb.append(" timeZoneID=\"").append(geoLocation.getZoneId().getId()).append("\"");
		sb.append(" timeZoneOffset=\"").append(offsetHours).append("\"");
		//sb.append(" useElevationAllZmanim=\"").append(astronomicalCalendar.useElevationAllZmanim()).append("\""); //TODO likely using reflection
		sb.append(">\n");

		Method[] theMethods = astronomicalCalendar.getClass().getMethods();
		String tagName;
		Object value;
		List<Zman> dateList = new ArrayList<>();
		List<Zman> durationList = new ArrayList<>();
		List<String> otherList = new ArrayList<>();
		for (Method theMethod : theMethods) {
			if (includeMethod(theMethod)) {
				tagName = theMethod.getName().substring(3);
				// String returnType = theMethods[i].getReturnType().getName();
				try {
					value = theMethod.invoke(astronomicalCalendar, (Object[]) null);
					if (value == null) {
						otherList.add("<" + tagName + ">N/A</" + tagName + ">");
					} else if (value instanceof Instant) {
						dateList.add(new Zman((Instant) value, tagName));
					} else if (value instanceof Duration) {// shaah zmanis
						durationList.add(new Zman((Duration)value, tagName));
					} else { // will probably never enter this block, but is present to be future-proof
						otherList.add("<" + tagName + ">" + value + "</" + tagName + ">");
					}
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		}
		Zman zman;
		dateList.sort(Zman.DATE_ORDER);

		for (int i = 0; i < dateList.size(); i++) {
			zman = dateList.get(i);
			sb.append("\t<").append(zman.getLabel()).append(">");
			sb.append(xsdFormatter.format(zman.getZman()));
			sb.append("</").append(zman.getLabel()).append(">\n");
		}
		durationList.sort(Zman.DURATION_ORDER);
		for (int i = 0; i < durationList.size(); i++) {
			zman = durationList.get(i);
			sb.append("\t<" + zman.getLabel()).append(">");
			sb.append(formatter.format(zman.getDuration())).append("</").append(zman.getLabel())
					.append(">\n");
		}

		for (int i = 0; i < otherList.size(); i++) {// will probably never enter this block
			sb.append("\t").append(otherList.get(i)).append("\n");
		}

		if (isAstronomicalCalendar) {
			sb.append("</AstronomicalTimes>");
		} else if (isComprehensiveZmanimCalendar) {
			sb.append("</Zmanim>");
		} else if (isZmanimCalendar) {
			sb.append("</BasicZmanim>");
		}
		return sb.toString();
	}
	
	/**
	 * A method that returns a JSON formatted <code>String</code> representing the serialized <code>Object</code>. The
	 * format used is:
	 * <pre>
	 * {
	 *    &quot;metadata&quot;:{
	 *      &quot;date&quot;:&quot;1969-02-08&quot;,
	 *      &quot;type&quot;:&quot;com.kosherjava.zmanim.AstronomicalCalendar&quot;,
	 *      &quot;algorithm&quot;:&quot;US Naval Almanac Algorithm&quot;,
	 *      &quot;location&quot;:&quot;Montreal, Quebec&quot;,
	 *      &quot;latitude&quot;:&quot;45.497&quot;,
	 *      &quot;longitude&quot;:&quot;-73.63&quot;,
	 *      &quot;elevation:&quot;85.0&quot;,
	 *      &quot;timeZoneName&quot;:&quot;Eastern Standard Time&quot;,
	 *      &quot;timeZoneID&quot;:&quot;America/New_York&quot;,
	 *      &quot;timeZoneOffset&quot;:&quot;-5&quot;},
	 *    &quot;AstronomicalTimes&quot;:{
	 *     &quot;SeaLevelSunset&quot;:&quot;1969-02-08T17:11:26-05:00&quot;,
	 *     &quot;TemporalHour&quot;:&quot;PT50M23.259S&quot;
	 *     ...
	 *     }
	 * }
	 * </pre>
	 * 
	 * Note that the output uses the <a href="http://www.w3.org/TR/xmlschema11-2/#dateTime">xsd:dateTime</a> format for
	 * times such as sunrise, and <a href="http://www.w3.org/TR/xmlschema11-2/#duration">xsd:duration</a> format for
	 * times that are a duration such as the length of a
	 * {@link com.kosherjava.zmanim.AstronomicalCalendar#getTemporalHour() temporal hour}.
	 * If a zman does not occur, the value "N/A" will be returned.
	 * 
	 * @param astronomicalCalendar the AstronomicalCalendar Object
	 * 
	 * @return The JSON <code>String</code> formatted as described above.
	 */
	public static String toJSON(AstronomicalCalendar astronomicalCalendar) {
		ZmanimFormatter formatter = new ZmanimFormatter(ZmanimFormatter.SEXAGESIMAL_XSD_FORMAT, DateTimeFormatter.ofPattern(
				"yyyy-MM-dd'T'HH:mm:ss"), astronomicalCalendar.getGeoLocation().getZoneId());
		DateTimeFormatter xsdFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssXXX")
				.withZone(astronomicalCalendar.getGeoLocation().getZoneId());
		DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd")
				.withZone(astronomicalCalendar.getGeoLocation().getZoneId());

		LocalDate localDate = astronomicalCalendar.getLocalDate();
		GeoLocation geoLocation = astronomicalCalendar.getGeoLocation();		
		ZonedDateTime lastMidnight = ZonedDateTime.of(astronomicalCalendar.getLocalDate(), LocalTime.MIDNIGHT,
				astronomicalCalendar.getGeoLocation().getZoneId());
		double offsetHours = lastMidnight.getOffset().getTotalSeconds() / 3600.0;
		String timeZoneName = lastMidnight.format(DateTimeFormatter.ofPattern("zzzz", Locale.getDefault()));

		StringBuilder sb = new StringBuilder("{\n\"metadata\":{\n");
		sb.append("\t\"date\":\"").append(df.format(localDate)).append("\",\n");
		sb.append("\t\"type\":\"").append(astronomicalCalendar.getClass().getName()).append("\",\n");
		sb.append("\t\"algorithm\":\"").append(astronomicalCalendar.getAstronomicalCalculator().getCalculatorName()).append("\",\n");
		sb.append("\t\"location\":\"").append(geoLocation.getLocationName()).append("\",\n");
		sb.append("\t\"latitude\":\"").append(geoLocation.getLatitude()).append("\",\n");
		sb.append("\t\"longitude\":\"").append(geoLocation.getLongitude()).append("\",\n");
		sb.append("\t\"elevation\":\"").append(geoLocation.getElevation()).append("\",\n");
		sb.append("\t\"timeZoneName\":\"").append(timeZoneName).append("\",\n");
		sb.append("\t\"timeZoneID\":\"").append(geoLocation.getZoneId().getId()).append("\",\n");
		sb.append("\t\"timeZoneOffset\":\"").append(offsetHours).append("\"");
		sb.append("},\n\"");

		switch (astronomicalCalendar.getClass().getName()) {
			case "com.kosherjava.zmanim.AstronomicalCalendar":
				sb.append("AstronomicalTimes");
				break;
			case "com.kosherjava.zmanim.ComprehensiveZmanimCalendar":
				sb.append("Zmanim");
				break;
			case "com.kosherjava.zmanim.ZmanimCalendar":
				sb.append("BasicZmanim");
				break;
		}
		sb.append("\":{\n");
		Method[] theMethods = astronomicalCalendar.getClass().getMethods();
		String tagName;
		Object value;
		List<Zman> dateList = new ArrayList<>();
		List<Zman> durationList = new ArrayList<>();
		List<String> otherList = new ArrayList<>();
		for (Method theMethod : theMethods) {
			if (includeMethod(theMethod)) {
				tagName = theMethod.getName().substring(3);
				// String returnType = theMethods[i].getReturnType().getName();
				try {
					value = theMethod.invoke(astronomicalCalendar, (Object[]) null);
					if (value == null) {
						otherList.add("\"" + tagName + "\":\"N/A\",");
					} else if (value instanceof Instant) {
						dateList.add(new Zman((Instant) value, tagName));
					} else if (value instanceof Duration) {// shaah zmanis
						durationList.add(new Zman((Duration)value, tagName));
					} else { // will probably never enter this block, but is present to be future-proof
						otherList.add("\"" + tagName + "\":\"" + value + "\",");
					}
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		}
		Zman zman;
		dateList.sort(Zman.DATE_ORDER);
		for (int i = 0; i < dateList.size(); i++) {
			zman = dateList.get(i);
			sb.append("\t\"").append(zman.getLabel()).append("\":\"");
			sb.append(xsdFormatter.format(zman.getZman()));
			sb.append("\",\n");
		}
		durationList.sort(Zman.DURATION_ORDER);
		for (int i = 0; i < durationList.size(); i++) {
			zman = durationList.get(i);
			sb.append("\t\"" + zman.getLabel()).append("\":\"");
			sb.append(formatter.format(zman.getDuration())).append("\",\n");
		}

		for (int i = 0; i < otherList.size(); i++) {// will probably never enter this block
			sb.append("\t").append(otherList.get(i)).append("\n");
		}
		sb.setLength(sb.length() - 2);
		sb.append("}\n}");
		return sb.toString();
	}

	/**
	 * Determines if a method should be output by the {@link #toXML(AstronomicalCalendar)}
	 * 
	 * @param method the method in question
	 * @return if the method should be included in serialization
	 */
	private static boolean includeMethod(Method method) {
		List<String> methodWhiteList = new ArrayList<>();
		List<String> methodBlackList = new ArrayList<>();

		if (methodWhiteList.contains(method.getName()))
			return true;
		if (methodBlackList.contains(method.getName()))
			return false;

		if (method.getParameterTypes().length > 0)
			return false; // Skip get methods with parameters since we do not know what value to pass
		if (!method.getName().startsWith("get"))
			return false;

		return method.getReturnType().getName().endsWith("Instant") || method.getReturnType().getName().endsWith("Duration");
	}
}
